#! /usr/bin/env php
<?php

require_once dirname(__FILE__).'/library/class/EC2controller.php';
defined('ROOT') || define('ROOT', dirname(__FILE__));


try {
    $controller = new EC2controller;

    if (isset($argv[1])) {
        $argv[1] = trim($argv[1]);

        // パラメータあり
        if (preg_match('/^ec2(-[0-9]+){4}\.ap-northeast-1\.compute\.amazonaws\.com$/', $argv[1])) {
            // DNSホスト名がパラメータの場合
            $controller->connectHost($argv[1]);
        
        } else {
            // 数字パラメータの場合
            $controller->connect($argv[1]);
        }
    
    } else {
        // パラメータなし
        // EC2インスタンスのリストを表示する
        $controller->getInstanceList();
    }


} catch (\Exception $e) {
    throw $e;
}

