#! /usr/bin/env php
<?php

require_once dirname(__FILE__).'/library/class/EC2controller.php';
defined('ROOT') || define('ROOT', dirname(__FILE__));


try {
    $controller = new EC2controller;

    if (isset($argv[1])) {
        // パラメータあり
        $controller->connect($argv[1]);
    
    } else {
        // パラメータなし
        // EC2インスタンスのリストを表示する
        $controller->getInstanceList();
    }


} catch (\Exception $e) {
    throw $e;
}

